# Generated by Django 6.0 on 2025-12-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=50)),
                ('specs', models.TextField()),
                ('images', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
